### ISSUE TITLE
Response to request for testing

### ISSUE THREAD

**Issue by samnob** [n0tOdd/n0tFlix#1]
I've installed your current manifest https://raw.githubusercontent.com/n0tOdd/n0tFlix/main/Manifest/n0tFlix-Manifest-Template.json
and the included plugin n0tFlix.Plugin.TvSubtitles

This is on a small arm64 SBC: rockpro64

plugin appears to install, but shows up in the web interface marked "Status: Malfunctioned" and I have this in my logs:
Feb 04 13:53:30 rockpro64 jellyfin[1398948]: [13:53:30] [INF] New plugin installed: n0tFlix.Plugin.TvSubtitles 12.0.0.0
Feb 04 13:53:51 rockpro64 jellyfin[1399116]: [13:53:51] [ERR] Failed to load assembly /var/lib/jellyfin/plugins/n0tFlix.Plugin.TvSubtitles_12.0.0.0/n0tFlix.Plugin.TvSubtitles.dll. Unknown exception was thrown. Disabling plugin.
Feb 04 13:53:51 rockpro64 jellyfin[1399116]: System.BadImageFormatException: Could not load file or assembly 'n0tFlix.Plugin.TvSubtitles, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null'. Reference assemblies should not be loaded for execution.  They can only be loaded in the Reflection-only loader context. (0x80131058)
Feb 04 13:53:51 rockpro64 jellyfin[1399116]: File name: 'n0tFlix.Plugin.TvSubtitles, Version=12.0.0.0, Culture=neutral, PublicKeyToken=null' ---> System.BadImageFormatException: Cannot load a reference assembly for execution.

**Comment by TheOddPirate** [comment]
Yeah im getting the same error myself, i think its the html parser anglesharp thats giving the error, il try o to replace it later this week

**Comment by TheOddPirate** [comment]
ITS ALIVE =D
i was using the fron netframework, changed from net6.0 to net5.0 and now its coming up as a active plugin
gonna eat some breakfast and try to upgrade some more plugins soon

**Comment by TheOddPirate** [comment]
ah damnit, and we are back on malfunctioned

**Comment by TheOddPirate** [comment]
Finally the first plugin is working, the yifi subtitle plugin is working here now, please test it out and give me some feedback

**Comment by samnob** [comment]
Yeah the installation process seems to be running smoothly. The yifi plugin now opens a settings dialog pre-populated with the 
 credentials from my opensubtitles.com plugin. Not sure if it's actually working, I have this in my logs:

Feb 06 00:44:48 rockpro64 jellyfin[2222545]: [00:44:48] [ERR] Error downloading subtitles from Yifi
Feb 06 00:44:48 rockpro64 jellyfin[2222545]: System.UriFormatException: Invalid URI: Invalid port specified.
Feb 06 00:44:48 rockpro64 jellyfin[2222545]:    at System.Uri.CreateThis(String uri, Boolean dontEscape, UriKind uriKind)
Feb 06 00:44:48 rockpro64 jellyfin[2222545]:    at n0tFlix.Plugin.Yifi.SubtitleDownloader.Search(SubtitleSearchRequest request, CancellationToken cancellationToken)
Feb 06 00:44:48 rockpro64 jellyfin[2222545]:    at MediaBrowser.Providers.Subtitles.SubtitleManager.SearchSubtitles(SubtitleSearchRequest request, CancellationToken cancellationToken)

The yt-dl and NRK plugins also seem to install without issue. And the NRK collection now appears on my home screen with populated categories, however the videos don't actually play yet:

Feb 06 13:17:12 rockpro64 jellyfin[3265207]: [13:17:12] [INF] Loaded assembly n0tFlix.Helpers, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Nrk_0.0.1.3/n0tFlix.Helpers.dll
Feb 06 13:17:12 rockpro64 jellyfin[3265207]: [13:17:12] [INF] Loaded assembly n0tFlix.Plugin.NRK, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null from /var/lib/jellyfin/plugins/Nrk_0.0.1.3/n0tFlix.Plugin.NRK.dll
Feb 06 13:17:23 rockpro64 jellyfin[3265207]: [13:17:23] [INF] Loaded plugin: Nrk 0.0.1.3
Feb 06 13:17:23 rockpro64 jellyfin[3265207]: [13:17:23] [ERR] n0tFlix.Plugin.NRK initialised and ready for use
Feb 06 13:17:25 rockpro64 jellyfin[3265207]: [13:17:25] [ERR] n0tFlix.Plugin.NRK initialised and ready for use
Feb 06 13:17:28 rockpro64 jellyfin[3265207]: [13:17:28] [INF] StartupTrigger fired for task: NRK
Feb 06 13:17:28 rockpro64 jellyfin[3265207]: [13:17:28] [INF] Executing NRK
Feb 06 13:17:29 rockpro64 jellyfin[3265207]: [13:17:29] [INF] We Found  categories for nrk
Feb 06 13:17:37 rockpro64 jellyfin[3265207]: [13:17:37] [ERR] Grabbing stream data for https://psapi.nrk.no/playback/manifest/KOID23007818
Feb 06 13:17:38 rockpro64 jellyfin[3265207]:    at n0tFlix.Plugin.NRK.Worker.GetMediaSourceInfo(String id, ILogger logger, CancellationToken cancellationToken)
Feb 06 13:17:38 rockpro64 jellyfin[3265207]:    at n0tFlix.Plugin.NRK.Channel.GetChannelItemMediaInfo(String id, CancellationToken cancellationToken)
Feb 06 13:17:38 rockpro64 jellyfin[3265207]: [13:17:38] [INF] NRK Completed after 0 minute(s) and 9 seconds
Feb 06 13:17:42 rockpro64 jellyfin[3265207]: [13:17:42] [ERR] Grabbing stream data for https://psapi.nrk.no/playback/manifest/KOID23007818
Feb 06 13:17:42 rockpro64 jellyfin[3265207]:    at n0tFlix.Plugin.NRK.Worker.GetMediaSourceInfo(String id, ILogger logger, CancellationToken cancellationToken)
Feb 06 13:17:42 rockpro64 jellyfin[3265207]:    at n0tFlix.Plugin.NRK.Channel.GetChannelItemMediaInfo(String id, CancellationToken cancellationToken)

**Comment by TheOddPirate** [comment]
The nrk videos are fixed now, or most of them are, im having a hard time finiding the variable to know if its still possible to watch that show or not so its bringing in some old movies/series

yeah the subtitle plugins are a  copy of the opensubtitles plugin, i should probably just remove the html code, but im telling myself that if i look long enough at them il understand how html works and i can start making some ui too

**Comment by TheOddPirate** [comment]
okay i was to fast with saying the nrk channel is working, on my develoepr laptop it runs just perfect, but on my ubuntu server all i get is a black screen

**Comment by TheOddPirate** [comment]
Okay so i disabled my local jellyfin installation and setup a new one in docker and there the channel works perfectly again

**Comment by samnob** [comment]
Sounds good, to uninstall the old NRK I had to delete the folder by hand from my plugins dir on the server, the jellyfin UI would just sit and spin. I don't know if this was related to the following issues.
Unfortunately I wasn't able to test the new NRK yet as something is currently wrong with like the formatting of the checksums at: https://raw.githubusercontent.com/n0tOdd/n0tFlix/main/Manifest/n0tFlix-Manifest-Template.json? At first the "Update Plugins" scheduled task failed:
[2022-02-07 06:14:37.532 -07:00] [INF] "Update Plugins" Failed after 0 minute(s) and 2 seconds
[2022-02-07 06:14:37.535 -07:00] [INF] ExecuteQueuedTasks
[2022-02-07 06:14:51.680 -07:00] [INF] Executing "Update Plugins"
[2022-02-07 06:14:54.290 -07:00] [ERR] The checksums didn't match while installing "Yifi", expected: "4D-3D-13-2F-D5-68-91-7B-6B-E0-1C-C9-62-55-15-6C", got: "4D3D132FD568917B6BE01CC96255156C"
[2022-02-07 06:14:54.291 -07:00] [ERR] Package installation failed
System.IO.InvalidDataException: The checksum of the received data doesn't match.
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.PerformPackageInstallation(InstallationInfo package, PluginStatus status, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackageInternal(InstallationInfo package, CancellationToken cancellationToken)
   at Emby.Server.Implementations.Updates.InstallationManager.InstallPackage(InstallationInfo package, CancellationToken cancellationToken)
   
So uninstalled Yifi (again deleting from the server's filesystem)
But now get this when trying to install NRK:
Feb 07 06:45:20 rockpro64 jellyfin[3979108]: [06:45:20] [ERR] The checksums didn't match while installing NRK, expected: F4-06-09-C3-B0-D5-31-B0-23-CD-CF-3B-42-EB-BB-4E, got: F40609C3B0D531B023CDCF3B42EBBB4E
Feb 07 06:45:20 rockpro64 jellyfin[3979108]: [06:45:20] [ERR] Package installation failed
Feb 07 06:45:20 rockpro64 jellyfin[3979108]: [06:45:20] [ERR] Error processing request. URL POST /Packages/Installed/NRK.

If we want to wrestle the repo issues a different time LMK and I can I pull the NRK manually.

**Comment by TheOddPirate** [comment]
Yeah the uninstall thing i think is because i was using the wrong version number in my menifest.

Thanks for telling me about the checksum, that was a test of a app to auto create the manifest file on each compile and i see now that it ads a extra - to the checksum, il do a update for that after school tomorow

**Comment by TheOddPirate** [comment]
okay the manifest should be working now

**Comment by samnob** [comment]
Thanks Odd looks great.
